[package]

name = "fireplace_server"
version  = "0.0.1"
authors = ["Tucker Morgan Tucker.bull.morgan@gmail.com"]

[dependencies]

rand = "0.3.0"
rustc-serialize = "0.3"
rhai = "0.4.0"
regex = "0.1"
hlua = "0.3"
time = "0.1"
mongodb = "0.3.5"
bson = "0.9"
serde = "1.0.15"
serde_derive = "1.0.15"